# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lineItem.proto

require 'google/protobuf'

require 'product_pb'
require 'supplier_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lineItem.proto", :syntax => :proto3) do
    add_message "store.LineItemRequest" do
      optional :id, :uint32, 1
    end
    add_message "store.LineItem" do
      optional :id, :uint32, 1
      optional :product, :message, 2, "store.Product"
      optional :quantity, :uint32, 3
      optional :total_cost, :double, 4
      optional :supplier, :message, 5, "store.Supplier"
      optional :source, :string, 6
    end
  end
end

module Store
  LineItemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.LineItemRequest").msgclass
  LineItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.LineItem").msgclass
end
