# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product.proto", :syntax => :proto3) do
    add_message "store.Product" do
      optional :name, :string, 1
      optional :cost, :double, 2
    end
  end
end

module Store
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.Product").msgclass
end
