# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

require 'google/protobuf'

require 'lineItem_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("store.proto", :syntax => :proto3) do
  end
end

module Store
end
