# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: store.proto for package 'store'

require 'grpc'
require 'store_pb'

module Store
  module Store
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'store.Store'

      rpc :GetLineItem, LineItemRequest, LineItem
    end

    Stub = Service.rpc_stub_class
  end
end
