# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supplier.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("supplier.proto", :syntax => :proto3) do
    add_message "store.Supplier" do
      optional :name, :string, 1
      optional :country, :string, 2
    end
  end
end

module Store
  Supplier = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.Supplier").msgclass
end
