// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lineItem.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LineItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineItemRequest) Reset()         { *m = LineItemRequest{} }
func (m *LineItemRequest) String() string { return proto.CompactTextString(m) }
func (*LineItemRequest) ProtoMessage()    {}
func (*LineItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84925267b1d0cb3a, []int{0}
}

func (m *LineItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineItemRequest.Unmarshal(m, b)
}
func (m *LineItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineItemRequest.Marshal(b, m, deterministic)
}
func (m *LineItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineItemRequest.Merge(m, src)
}
func (m *LineItemRequest) XXX_Size() int {
	return xxx_messageInfo_LineItemRequest.Size(m)
}
func (m *LineItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LineItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LineItemRequest proto.InternalMessageInfo

func (m *LineItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LineItem struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product              *Product  `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Quantity             uint32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalCost            float64   `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Supplier             *Supplier `protobuf:"bytes,5,opt,name=supplier,proto3" json:"supplier,omitempty"`
	Source               string    `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LineItem) Reset()         { *m = LineItem{} }
func (m *LineItem) String() string { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()    {}
func (*LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_84925267b1d0cb3a, []int{1}
}

func (m *LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineItem.Unmarshal(m, b)
}
func (m *LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineItem.Marshal(b, m, deterministic)
}
func (m *LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineItem.Merge(m, src)
}
func (m *LineItem) XXX_Size() int {
	return xxx_messageInfo_LineItem.Size(m)
}
func (m *LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_LineItem proto.InternalMessageInfo

func (m *LineItem) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LineItem) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *LineItem) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *LineItem) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *LineItem) GetSupplier() *Supplier {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *LineItem) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*LineItemRequest)(nil), "store.LineItemRequest")
	proto.RegisterType((*LineItem)(nil), "store.LineItem")
}

func init() { proto.RegisterFile("lineItem.proto", fileDescriptor_84925267b1d0cb3a) }

var fileDescriptor_84925267b1d0cb3a = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0x49, 0x75, 0x6a, 0xe7, 0xc9, 0x64, 0x20, 0x0b, 0x09, 0x05, 0x21, 0xce, 0x2a, 0x20,
	0x74, 0xa1, 0x9f, 0xe0, 0x4a, 0x70, 0x21, 0xf1, 0x03, 0xa4, 0xb6, 0x59, 0x04, 0x6a, 0x5f, 0x9a,
	0xbc, 0x2c, 0xfc, 0x3f, 0x3f, 0x4c, 0x48, 0xd3, 0x2e, 0x5c, 0xde, 0xf3, 0xee, 0xe5, 0x24, 0xc0,
	0x27, 0x37, 0xdb, 0x57, 0xb2, 0xdf, 0x9d, 0x0f, 0x48, 0x28, 0x0e, 0x91, 0x30, 0xd8, 0xf6, 0xe4,
	0x03, 0x8e, 0x69, 0xa0, 0x95, 0xb6, 0x3c, 0x26, 0xef, 0x27, 0x67, 0xc3, 0x9a, 0x2f, 0x0f, 0x70,
	0x7e, 0x2b, 0x3b, 0x63, 0x97, 0x64, 0x23, 0x09, 0x0e, 0x95, 0x1b, 0x25, 0x53, 0x4c, 0x9f, 0x4c,
	0xe5, 0xc6, 0xcb, 0x2f, 0x83, 0x66, 0xeb, 0xfc, 0x3f, 0x0a, 0x0d, 0x37, 0x45, 0x20, 0x2b, 0xc5,
	0xf4, 0xed, 0x13, 0xef, 0xb2, 0xb7, 0x7b, 0x5f, 0xa9, 0xd9, 0xce, 0xa2, 0x85, 0x66, 0x49, 0xfd,
	0x4c, 0x8e, 0x7e, 0xe4, 0x55, 0xde, 0xef, 0x59, 0xdc, 0x03, 0x10, 0x52, 0x3f, 0x7d, 0x0e, 0x18,
	0x49, 0x5e, 0x2b, 0xa6, 0x99, 0x39, 0x66, 0xf2, 0x82, 0x91, 0xc4, 0x23, 0x34, 0xdb, 0xb3, 0xe5,
	0x21, 0x5b, 0xce, 0xc5, 0xf2, 0x51, 0xb0, 0xd9, 0x0b, 0xe2, 0x0e, 0xea, 0x88, 0x29, 0x0c, 0x56,
	0xd6, 0x8a, 0xe9, 0xa3, 0x29, 0xe9, 0xab, 0xce, 0x1f, 0x7e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xf1, 0x77, 0x52, 0x7c, 0x28, 0x01, 0x00, 0x00,
}
