// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0xc9, 0x2f,
	0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0xf8, 0x72, 0x32, 0xf3,
	0x52, 0x3d, 0x4b, 0x52, 0x73, 0x21, 0xc2, 0x46, 0x8e, 0x5c, 0xac, 0xc1, 0x20, 0x09, 0x21, 0x0b,
	0x2e, 0x6e, 0xf7, 0xd4, 0x12, 0x1f, 0xa8, 0xac, 0x90, 0x98, 0x1e, 0x44, 0x33, 0x4c, 0x20, 0x28,
	0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x8a, 0x1f, 0x4d, 0x5c, 0x89, 0x21, 0x89, 0x0d, 0x6c, 0x92,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x35, 0x79, 0xc8, 0x6f, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	GetLineItem(ctx context.Context, in *LineItemRequest, opts ...grpc.CallOption) (*LineItem, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) GetLineItem(ctx context.Context, in *LineItemRequest, opts ...grpc.CallOption) (*LineItem, error) {
	out := new(LineItem)
	err := c.cc.Invoke(ctx, "/store.Store/GetLineItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	GetLineItem(context.Context, *LineItemRequest) (*LineItem, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) GetLineItem(ctx context.Context, req *LineItemRequest) (*LineItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLineItem not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_GetLineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LineItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetLineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.Store/GetLineItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetLineItem(ctx, req.(*LineItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLineItem",
			Handler:    _Store_GetLineItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
